# Generated by Django 5.0.6 on 2024-06-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contractor_register',
            table='tb_Contractor_register',
        ),
    ]
