# Generated by Django 5.0.6 on 2024-06-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0002_alter_contractor_register_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='company',
        ),
    ]
