# Generated by Django 5.0.6 on 2024-06-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0003_remove_order_product_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='tp_id',
        ),
        migrations.AddField(
            model_name='order_product',
            name='product_type',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
