# Generated by Django 5.0.6 on 2024-06-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0004_remove_order_product_tp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='order_product',
            name='tp_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
