# Generated by Django 5.0.6 on 2024-06-12 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0005_remove_order_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='contact_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proapp.contractor_register'),
            preserve_default=False,
        ),
    ]
