# Generated by Django 5.0.6 on 2024-06-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proapp', '0006_order_product_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='order_product',
            name='status1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
